version: "3.3"
services:
  ros2-adapter:
      
    build: .
    network_mode: host
    pid: host
    privileged: true
    restart: always
    stop_grace_period: 1s
    volumes:
      - "/var/lib/formant:/var/lib/formant"
      - "/home/birdseye/ros_bags:/home/birdseye/ros_bags"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}


