version: "3.3"
services:
  ros2-adapter:
    image: berobotics/formant-ros2-adapter@sha256:9bb73592d5c35c63ec0bd40bb86f3680879cf8f18f20ad0fa65b19ca1313b262
    container_name: formant-ros2-adapter
    network_mode: host
    pid: host
    privileged: true
    restart: always
    stop_grace_period: 1s
    volumes:
      - "/var/lib/formant:/var/lib/formant"
      - "/home/birdseye/ros_bags:/home/birdseye/ros_bags"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
      FORMANT_ENABLE_ADAPTIVE_BITRATE: false
    depends_on:
      - formant-agent

  formant-agent:
    image: formant/agent@sha256:1f98a8c45a241b30a7090284b871f5abb81a2b1a9939d1cbe1931b299c5d62c1
    container_name: formant-agent
    network_mode: host
    pid: host
    privileged: true
    restart: always
    stop_grace_period: 1s
    volumes:
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/formant:/var/lib/formant"
      - "/home/birdseye/ros_bags:/home/birdseye/ros_bags"
      - "/home/birdseye/Birdseye:/home/birdseye/Birdseye"
      - "/home/birdseye/.ssh/:/root/.ssh"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
      FORMANT_DEBUG: "true"
      WEBRTC_INTERFACE: "wlp0s20f3"
      FORMANT_ENABLE_ADAPTIVE_BITRATE: false

