version: "3.3"
services:
  ros2-adapter:
    image: berobotics/formant-ros2-adapter
    build: .
    network_mode: host
    pid: host
    privileged: true
    restart: always
    stop_grace_period: 1s
    volumes:
      - "/var/lib/formant:/var/lib/formant"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
    depends_on:
      - formant-agent

  formant-agent:
    image: formant/agent
    container_name: formant-agent
    network_mode: host
    pid: host
    privileged: true
    restart: always
    stop_grace_period: 1s
    volumes:
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/formant:/var/lib/formant"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}


# uid=$(id -u formant)
# gid=$(id -g formant)
#     --user $uid:$gid \
#     --group-add audio \
#     --group-add video \
#     $ros_master_config \
#     $catkin_ws_config \
#     formant/agent:$tag


