name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: git remote add upstream git@github.com:FormantIO/ros2-adapter.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/master --no-commit --no-ff

      - name: Restore Docker file modifications
        run: |
          git checkout master -- docker-compose.yaml
          git checkout master -- Dockerfile
          git checkout master -- formant_ros2_adapter/scripts/config.json
          # Add more 'git checkout' commands for each modified Docker file

      - name: Commit changes
        run: |
          git commit -m "Sync with original repository, excluding Docker file modifications"
          git push origin/master master
