name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: git remote add upstream https://github.com/FormantIO/ros2-adapter.git

      - name: Fetch upstream changes
        run: git fetch upstream
          
      - name: Set Git committer identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
    
      - name: Merge upstream changes
        run: |
          git merge --strategy-option=theirs --allow-unrelated-histories upstream/master
          git checkout origin/master -- docker-compose.yaml Dockerfile formant_ros2_adapter/scripts/config.json

      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync with original repository, excluding Docker file modifications"

      - name: Create pull request
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          gh pr create --base origin/master --head "$branch_name" --title "Sync with original repository, excluding Docker file modifications" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
